
MAP = {
    'identifier': 'urn:oasis:names:tc:SAML:2.0:attrname-format:basic',
    'fro': {
        'spidCode': 'spidCode',
        'name': 'name',
        'familyName': 'familyName',
        'placeOfBirth': 'placeOfBirth',
        'countryOfBirth': 'countryOfBirth',
        'dateOfBirth': 'dateOfBirth',
        'gender': 'gender',
        'companyName': 'companyName',
        'registeredOffice': 'registeredOffice',
        'fiscalNumber': 'fiscalNumber',
        'ivaCode': 'ivaCode',
        'idCard': 'idCard',
        'mobilePhone': 'mobilePhone',
        'email': 'email',
        'address': 'address',
        'expirationDate': 'expirationDate',
        'digitalAddress': 'digitalAddress',
    },
    'to': {
        'spidCode': 'spidCode',
        'name': 'name',
        'familyName': 'familyName',
        'placeOfBirth': 'placeOfBirth',
        'countryOfBirth': 'countryOfBirth',
        'dateOfBirth': 'dateOfBirth',
        'gender': 'gender',
        'companyName': 'companyName',
        'registeredOffice': 'registeredOffice',
        'fiscalNumber': 'fiscalNumber',
        'ivaCode': 'ivaCode',
        'idCard': 'idCard',
        'mobilePhone': 'mobilePhone',
        'email': 'email',
        'address': 'address',
        'expirationDate': 'expirationDate',
        'digitalAddress': 'digitalAddress',
    }
}